# Generated by Django 3.2.15 on 2023-08-10 19:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0042_auto_20230723_1255'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderdetails',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Стоимость'),
            preserve_default=False,
        ),
    ]
