# Generated by Django 3.2.15 on 2023-09-02 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0044_auto_20230814_2156'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('R', 'Get_ready'), ('D', 'Delivery'), ('C', 'Completed')], default='N', max_length=1, verbose_name='Статус заказа'),
        ),
    ]
