# Generated by Django 3.2.15 on 2023-09-02 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0045_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('N', 'Новый'), ('R', 'Готовиться'), ('D', 'Доставляется'), ('C', 'Завершен')], db_index=True, default='N', max_length=1, verbose_name='Статус заказа'),
        ),
    ]
