# Generated by Django 3.2.15 on 2023-09-02 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0049_auto_20230902_2236'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('C', 'Наличные'), ('E', 'Электронные')], db_index=True, default='C', max_length=1, verbose_name='Способ оплаты'),
        ),
    ]
