# Generated by Django 3.2.15 on 2023-09-27 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0053_auto_20230926_2238'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='latitude',
            field=models.CharField(max_length=10, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='longitude',
            field=models.CharField(max_length=10, verbose_name='Долгота'),
        ),
    ]
