# Generated by Django 3.2.15 on 2023-10-01 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0054_auto_20230927_2137'),
    ]

    operations = [
        migrations.CreateModel(
            name='Geolocation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, unique=True, verbose_name='Адрес')),
                ('longitude', models.CharField(max_length=10, verbose_name='Долгота')),
                ('latitude', models.CharField(max_length=10, verbose_name='Широта')),
                ('last_update', models.DateField(auto_now=True, verbose_name='Дата последнего обновления')),
            ],
        ),
    ]
