# Generated by Django 3.2.15 on 2023-10-01 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcartapp', '0056_auto_20231001_2244'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geolocation',
            options={'verbose_name': 'Геолокация', 'verbose_name_plural': 'Геолокации'},
        ),
    ]
